# coding: utf-8

"""
    Comotion Dash DailyRun API

    Comotion Dash DailyRun API. These endpoints control and inspect the Daily ETL pipeline for a single Dash organisation.  They are served from the per-organisation frontend API rather than the main Dash `/v2` API, which is why they live in a separate specification and generate a separate client package. The organisation is determined by the hostname, so none of the operations take an organisation parameter. 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_dailyrun_api_client_lowlevel.models.execution import Execution

class TestExecution(unittest.TestCase):
    """Execution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Execution:
        """Test Execution
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Execution`
        """
        model = Execution()
        if include_optional:
            return Execution(
                name = 'DailyScheduledETL_training_20260108T100213Z',
                status = 'SUCCEEDED',
                start_date = '2026-01-08T10:02:14.025000+00:00',
                stop_date = '2026-01-08T11:14:52.331000+00:00'
            )
        else:
            return Execution(
        )
        """

    def testExecution(self):
        """Test Execution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
