# coding: utf-8

"""
    Comotion Dash DailyRun API

    Comotion Dash DailyRun API. These endpoints control and inspect the Daily ETL pipeline for a single Dash organisation.  They are served from the per-organisation frontend API rather than the main Dash `/v2` API, which is why they live in a separate specification and generate a separate client package. The organisation is determined by the hostname, so none of the operations take an organisation parameter. 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_dailyrun_api_client_lowlevel.models.daily_run_enabled import DailyRunEnabled

class TestDailyRunEnabled(unittest.TestCase):
    """DailyRunEnabled unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DailyRunEnabled:
        """Test DailyRunEnabled
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DailyRunEnabled`
        """
        model = DailyRunEnabled()
        if include_optional:
            return DailyRunEnabled(
                daily_run = True
            )
        else:
            return DailyRunEnabled(
                daily_run = True,
        )
        """

    def testDailyRunEnabled(self):
        """Test DailyRunEnabled"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
