# coding: utf-8

"""
    Comotion Dash DailyRun API

    Comotion Dash DailyRun API. These endpoints control and inspect the Daily ETL pipeline for a single Dash organisation.  They are served from the per-organisation frontend API rather than the main Dash `/v2` API, which is why they live in a separate specification and generate a separate client package. The organisation is determined by the hostname, so none of the operations take an organisation parameter. 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_dailyrun_api_client_lowlevel.api.daily_run_api import DailyRunApi


class TestDailyRunApi(unittest.TestCase):
    """DailyRunApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DailyRunApi()

    def tearDown(self) -> None:
        pass

    def test_get_daily_run_enabled(self) -> None:
        """Test case for get_daily_run_enabled

        Get whether the daily run is enabled
        """
        pass

    def test_get_daily_run_execution_status(self) -> None:
        """Test case for get_daily_run_execution_status

        Get Daily ETL pipeline execution information
        """
        pass

    def test_start_daily_run_execution(self) -> None:
        """Test case for start_daily_run_execution

        Start a Daily ETL pipeline execution
        """
        pass

    def test_update_daily_run_enabled(self) -> None:
        """Test case for update_daily_run_enabled

        Enable or disable the daily run
        """
        pass


if __name__ == '__main__':
    unittest.main()
