{% set data = load_setup_py_data() %}


package:
  name: comotion-sdk
  version: {{ data.get('version') }}

source:
  # Relative path to the parent directory.
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ data.get('version') }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entrypoints:
    - comotion = comotion.cli:cli

requirements:
  build:
    - pip
    - python
    - setuptools
  host:
    - python
  run:
    - python
    - jpype1



# conda build conda-recipe --output-folder ./conda-build/
