# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_api.loads_api import LoadsApi


class TestLoadsApi(unittest.TestCase):
    """LoadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoadsApi()

    def tearDown(self) -> None:
        pass

    def test_create_load(self) -> None:
        """Test case for create_load

        Create a new load
        """
        pass


if __name__ == '__main__':
    unittest.main()
