# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.load_id import LoadId

class TestLoadId(unittest.TestCase):
    """LoadId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadId:
        """Test LoadId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadId`
        """
        model = LoadId()
        if include_optional:
            return LoadId(
                load_id = '20231117085806_355d42f6_0684_4b8f_b274_225bf7237494'
            )
        else:
            return LoadId(
                load_id = '20231117085806_355d42f6_0684_4b8f_b274_225bf7237494',
        )
        """

    def testLoadId(self):
        """Test LoadId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
