# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.commit_load202_response import CommitLoad202Response

class TestCommitLoad202Response(unittest.TestCase):
    """CommitLoad202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitLoad202Response:
        """Test CommitLoad202Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitLoad202Response`
        """
        model = CommitLoad202Response()
        if include_optional:
            return CommitLoad202Response(
                message = ''
            )
        else:
            return CommitLoad202Response(
        )
        """

    def testCommitLoad202Response(self):
        """Test CommitLoad202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
