# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.load import Load

class TestLoad(unittest.TestCase):
    """Load unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Load:
        """Test Load
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Load`
        """
        model = Load()
        if include_optional:
            return Load(
                load_type = 'APPEND_ONLY',
                table_name = 'q2c3v8s7djuy2zmetozkhdomha2bae48b9ocvx9o64ow3eg8p7qw_qklp7l5y121fogx',
                load_as_service_client_id = '',
                partitions = [
                    ''
                    ]
            )
        else:
            return Load(
                load_type = 'APPEND_ONLY',
                table_name = 'q2c3v8s7djuy2zmetozkhdomha2bae48b9ocvx9o64ow3eg8p7qw_qklp7l5y121fogx',
        )
        """

    def testLoad(self):
        """Test Load"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
