# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.query_text import QueryText

class TestQueryText(unittest.TestCase):
    """QueryText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryText:
        """Test QueryText
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryText`
        """
        model = QueryText()
        if include_optional:
            return QueryText(
                query = 'select 'hello' --should not be multiline'
            )
        else:
            return QueryText(
                query = 'select 'hello' --should not be multiline',
        )
        """

    def testQueryText(self):
        """Test QueryText"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
