# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_api_client_lowlevel.api.loads_api import LoadsApi


class TestLoadsApi(unittest.TestCase):
    """LoadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoadsApi()

    def tearDown(self) -> None:
        pass

    def test_commit_load(self) -> None:
        """Test case for commit_load

        Commit a load operation
        """
        pass

    def test_create_load(self) -> None:
        """Test case for create_load

        Create a new load
        """
        pass

    def test_generate_presigned_url_for_file_upload(self) -> None:
        """Test case for generate_presigned_url_for_file_upload

        Generate presigned URL for file upload
        """
        pass

    def test_get_load_metadata(self) -> None:
        """Test case for get_load_metadata

        Get load metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
