# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_api_client_lowlevel.api.queries_api import QueriesApi


class TestQueriesApi(unittest.TestCase):
    """QueriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueriesApi()

    def tearDown(self) -> None:
        pass

    def test_download_csv(self) -> None:
        """Test case for download_csv

        Download the csv result file of a query
        """
        pass

    def test_get_query(self) -> None:
        """Test case for get_query

        Get information about a query
        """
        pass

    def test_get_query_results(self) -> None:
        """Test case for get_query_results

        Get paginated results of a query
        """
        pass

    def test_run_query(self) -> None:
        """Test case for run_query

        Run a query
        """
        pass

    def test_stop_query(self) -> None:
        """Test case for stop_query

        Stop a running query
        """
        pass


if __name__ == '__main__':
    unittest.main()
