# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.query import Query

class TestQuery(unittest.TestCase):
    """Query unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Query:
        """Test Query
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Query`
        """
        model = Query()
        if include_optional:
            return Query(
                query = 'select 'hello'',
                query_id = '06ba1d95-8c4f-460c-90b3-bc68fddf2fde',
                statement_type = 'DDL',
                status = comodash_api_client_lowlevel.models.query_status.Query_status(
                    state = 'SUCCEEDED', 
                    submission_date_time = '11-28-2021 18:51:01', 
                    completion_date_time = '11-28-2021 18:53:01', )
            )
        else:
            return Query(
        )
        """

    def testQuery(self):
        """Test Query"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
