"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import comodash_api_client_lowlevel
from comodash_api_client_lowlevel.model.query_text import QueryText


class TestQueryText(unittest.TestCase):
    """QueryText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryText(self):
        """Test QueryText"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryText()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
