"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import comodash_api_client_lowlevel
from comodash_api_client_lowlevel.model.query_status import QueryStatus


class TestQueryStatus(unittest.TestCase):
    """QueryStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryStatus(self):
        """Test QueryStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
