# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comodash_api_client_lowlevel
from comodash_api_client_lowlevel.models.download_file_location import DownloadFileLocation  # noqa: E501
from comodash_api_client_lowlevel.rest import ApiException

class TestDownloadFileLocation(unittest.TestCase):
    """DownloadFileLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DownloadFileLocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comodash_api_client_lowlevel.models.download_file_location.DownloadFileLocation()  # noqa: E501
        if include_optional :
            return DownloadFileLocation(
                location = ''
            )
        else :
            return DownloadFileLocation(
        )

    def testDownloadFileLocation(self):
        """Test DownloadFileLocation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
