"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import comodash_api_client_lowlevel
from comodash_api_client_lowlevel.model.query_status import QueryStatus
globals()['QueryStatus'] = QueryStatus
from comodash_api_client_lowlevel.model.query import Query


class TestQuery(unittest.TestCase):
    """Query unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuery(self):
        """Test Query"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Query()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
