"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import comodash_api_client_lowlevel
from comodash_api_client_lowlevel.model.query_id import QueryId


class TestQueryId(unittest.TestCase):
    """QueryId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryId(self):
        """Test QueryId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
