# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.commit_load200_response import CommitLoad200Response

class TestCommitLoad200Response(unittest.TestCase):
    """CommitLoad200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitLoad200Response:
        """Test CommitLoad200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitLoad200Response`
        """
        model = CommitLoad200Response()
        if include_optional:
            return CommitLoad200Response(
                message = ''
            )
        else:
            return CommitLoad200Response(
        )
        """

    def testCommitLoad200Response(self):
        """Test CommitLoad200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
