# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.migration import Migration

class TestMigration(unittest.TestCase):
    """Migration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Migration:
        """Test Migration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Migration`
        """
        model = Migration()
        if include_optional:
            return Migration(
                migration_type = 'FULL_MIGRATION',
                clear_out_new_lake = 'DO_NOT_CLEAR_OUT'
            )
        else:
            return Migration(
                migration_type = 'FULL_MIGRATION',
        )
        """

    def testMigration(self):
        """Test Migration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
