"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import comodash_api_client_lowlevel
from comodash_api.queries_api import QueriesApi  # noqa: E501


class TestQueriesApi(unittest.TestCase):
    """QueriesApi unit test stubs"""

    def setUp(self):
        self.api = QueriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_csv(self):
        """Test case for download_csv

        Download the csv result file of a query  # noqa: E501
        """
        pass

    def test_get_query(self):
        """Test case for get_query

        Get information about a query  # noqa: E501
        """
        pass

    def test_get_query_results(self):
        """Test case for get_query_results

        Get paginated results of a query  # noqa: E501
        """
        pass

    def test_run_query(self):
        """Test case for run_query

        Run a query  # noqa: E501
        """
        pass

    def test_stop_query(self):
        """Test case for stop_query

        Stop a running query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
