# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comodash_api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_commit_load(self) -> None:
        """Test case for commit_load

        Commit a load operation
        """
        pass

    def test_create_load(self) -> None:
        """Test case for create_load

        Create a new load
        """
        pass


if __name__ == '__main__':
    unittest.main()
