# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.load_meta_data import LoadMetaData

class TestLoadMetaData(unittest.TestCase):
    """LoadMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadMetaData:
        """Test LoadMetaData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadMetaData`
        """
        model = LoadMetaData()
        if include_optional:
            return LoadMetaData(
                load_status = 'OPEN',
                error_type = '',
                error_messages = {
                    'key' : ''
                    }
            )
        else:
            return LoadMetaData(
        )
        """

    def testLoadMetaData(self):
        """Test LoadMetaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
