# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from comodash_api_client_lowlevel.models.query_status import QueryStatus

class TestQueryStatus(unittest.TestCase):
    """QueryStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryStatus:
        """Test QueryStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryStatus`
        """
        model = QueryStatus()
        if include_optional:
            return QueryStatus(
                state = 'SUCCEEDED',
                submission_date_time = '11-28-2021 18:51:01',
                completion_date_time = '11-28-2021 18:53:01'
            )
        else:
            return QueryStatus(
        )
        """

    def testQueryStatus(self):
        """Test QueryStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
