# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LoadMetaDataErrorMessagesInner(BaseModel):
    """
    LoadMetaDataErrorMessagesInner
    """ # noqa: E501
    error_type: Optional[StrictStr] = Field(default=None, description="type of error for which the message is shown", alias="ErrorType")
    error_message: Optional[StrictStr] = Field(default=None, description="error message", alias="ErrorMessage")
    check_result: Optional[StrictStr] = Field(default=None, description="error state", alias="CheckResult")
    __properties: ClassVar[List[str]] = ["ErrorType", "ErrorMessage", "CheckResult"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoadMetaDataErrorMessagesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if error_type (nullable) is None
        # and model_fields_set contains the field
        if self.error_type is None and "error_type" in self.model_fields_set:
            _dict['ErrorType'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['ErrorMessage'] = None

        # set to None if check_result (nullable) is None
        # and model_fields_set contains the field
        if self.check_result is None and "check_result" in self.model_fields_set:
            _dict['CheckResult'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LoadMetaDataErrorMessagesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ErrorType": obj.get("ErrorType"),
            "ErrorMessage": obj.get("ErrorMessage"),
            "CheckResult": obj.get("CheckResult")
        })
        return _obj


