# coding: utf-8

"""
    Comotion Dash API

    Comotion Dash API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from comodash_api_client_lowlevel.configuration import Configuration


class QueryStatusAllOfStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'state': 'str',
        'submission_date_time': 'str',
        'completion_date_time': 'str'
    }

    attribute_map = {
        'state': 'state',
        'submission_date_time': 'submissionDateTime',
        'completion_date_time': 'completionDateTime'
    }

    def __init__(self, state=None, submission_date_time=None, completion_date_time=None, local_vars_configuration=None):  # noqa: E501
        """QueryStatusAllOfStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._state = None
        self._submission_date_time = None
        self._completion_date_time = None
        self.discriminator = None

        if state is not None:
            self.state = state
        if submission_date_time is not None:
            self.submission_date_time = submission_date_time
        if completion_date_time is not None:
            self.completion_date_time = completion_date_time

    @property
    def state(self):
        """Gets the state of this QueryStatusAllOfStatus.  # noqa: E501


        :return: The state of this QueryStatusAllOfStatus.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this QueryStatusAllOfStatus.


        :param state: The state of this QueryStatusAllOfStatus.  # noqa: E501
        :type state: str
        """
        allowed_values = ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and state not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def submission_date_time(self):
        """Gets the submission_date_time of this QueryStatusAllOfStatus.  # noqa: E501


        :return: The submission_date_time of this QueryStatusAllOfStatus.  # noqa: E501
        :rtype: str
        """
        return self._submission_date_time

    @submission_date_time.setter
    def submission_date_time(self, submission_date_time):
        """Sets the submission_date_time of this QueryStatusAllOfStatus.


        :param submission_date_time: The submission_date_time of this QueryStatusAllOfStatus.  # noqa: E501
        :type submission_date_time: str
        """

        self._submission_date_time = submission_date_time

    @property
    def completion_date_time(self):
        """Gets the completion_date_time of this QueryStatusAllOfStatus.  # noqa: E501


        :return: The completion_date_time of this QueryStatusAllOfStatus.  # noqa: E501
        :rtype: str
        """
        return self._completion_date_time

    @completion_date_time.setter
    def completion_date_time(self, completion_date_time):
        """Sets the completion_date_time of this QueryStatusAllOfStatus.


        :param completion_date_time: The completion_date_time of this QueryStatusAllOfStatus.  # noqa: E501
        :type completion_date_time: str
        """

        self._completion_date_time = completion_date_time

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryStatusAllOfStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QueryStatusAllOfStatus):
            return True

        return self.to_dict() != other.to_dict()
