# coding: utf-8

"""
    Comotion Dash DailyRun API

    Comotion Dash DailyRun API. These endpoints control and inspect the Daily ETL pipeline for a single Dash organisation.  They are served from the per-organisation frontend API rather than the main Dash `/v2` API, which is why they live in a separate specification and generate a separate client package. The organisation is determined by the hostname, so none of the operations take an organisation parameter. 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from comodash_dailyrun_api_client_lowlevel.models.execution import Execution
from typing import Optional, Set
from typing_extensions import Self

class ExecutionStatus(BaseModel):
    """
    Execution information.  Which fields are populated depends on the `mode` used on the request, so every field is optional. In `list` mode only `executions` is set.  In `latest` and `last_successful` mode the execution fields are set directly on this object, or `message` is set when there is nothing to return. 
    """ # noqa: E501
    executions: Optional[List[Execution]] = Field(default=None, description="Recent executions.  Populated in `list` mode.")
    name: Optional[StrictStr] = Field(default=None, description="Execution name.  Populated in `latest` and `last_successful` mode.")
    status: Optional[StrictStr] = Field(default=None, description="Execution status.  Populated in `latest` and `last_successful` mode.")
    start_date: Optional[StrictStr] = Field(default=None, description="Execution start time.  Populated in `latest` and `last_successful` mode.", alias="startDate")
    stop_date: Optional[StrictStr] = Field(default=None, description="Execution stop time.  Populated in `latest` and `last_successful` mode.", alias="stopDate")
    message: Optional[StrictStr] = Field(default=None, description="Explanatory message, set in `last_successful` mode when there are no successful executions. ")
    __properties: ClassVar[List[str]] = ["executions", "name", "status", "startDate", "stopDate", "message"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in executions (list)
        _items = []
        if self.executions:
            for _item_executions in self.executions:
                if _item_executions:
                    _items.append(_item_executions.to_dict())
            _dict['executions'] = _items
        # set to None if stop_date (nullable) is None
        # and model_fields_set contains the field
        if self.stop_date is None and "stop_date" in self.model_fields_set:
            _dict['stopDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "executions": [Execution.from_dict(_item) for _item in obj["executions"]] if obj.get("executions") is not None else None,
            "name": obj.get("name"),
            "status": obj.get("status"),
            "startDate": obj.get("startDate"),
            "stopDate": obj.get("stopDate"),
            "message": obj.get("message")
        })
        return _obj


