# coding: utf-8

"""
    Comotion Dash DailyRun API

    Comotion Dash DailyRun API. These endpoints control and inspect the Daily ETL pipeline for a single Dash organisation.  They are served from the per-organisation frontend API rather than the main Dash `/v2` API, which is why they live in a separate specification and generate a separate client package. The organisation is determined by the hostname, so none of the operations take an organisation parameter. 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Execution(BaseModel):
    """
    A single Daily ETL pipeline execution.
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Step Functions execution name.  Always starts with `DailyScheduledETL_{orgName}_`. ")
    status: Optional[StrictStr] = Field(default=None, description="Step Functions execution status, for example RUNNING, SUCCEEDED, FAILED, TIMED_OUT or ABORTED.  Left unconstrained so that new Step Functions statuses do not break deserialisation. ")
    start_date: Optional[StrictStr] = Field(default=None, description="ISO 8601 timestamp of when the execution started.", alias="startDate")
    stop_date: Optional[StrictStr] = Field(default=None, description="ISO 8601 timestamp of when the execution stopped, or null while it is still running. ", alias="stopDate")
    __properties: ClassVar[List[str]] = ["name", "status", "startDate", "stopDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Execution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if stop_date (nullable) is None
        # and model_fields_set contains the field
        if self.stop_date is None and "stop_date" in self.model_fields_set:
            _dict['stopDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Execution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "status": obj.get("status"),
            "startDate": obj.get("startDate"),
            "stopDate": obj.get("stopDate")
        })
        return _obj


