# coding: utf-8

"""
    Comotion Dash DailyRun API

    Comotion Dash DailyRun API. These endpoints control and inspect the Daily ETL pipeline for a single Dash organisation.  They are served from the per-organisation frontend API rather than the main Dash `/v2` API, which is why they live in a separate specification and generate a separate client package. The organisation is determined by the hostname, so none of the operations take an organisation parameter. 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from comodash_dailyrun_api_client_lowlevel.models.running_execution import RunningExecution
from typing import Optional, Set
from typing_extensions import Self

class StartExecutionResponse(BaseModel):
    """
    Result of a start request.  Shared by the 200 and 409 responses, so `started` distinguishes the two outcomes. 
    """ # noqa: E501
    message: Optional[StrictStr] = None
    started: Optional[StrictBool] = Field(default=None, description="True when a new execution was started, false when one was already running.")
    execution_arn: Optional[StrictStr] = Field(default=None, description="ARN of the started execution.  Only set when `started` is true.", alias="executionArn")
    start_date: Optional[StrictStr] = Field(default=None, description="ISO 8601 start time of the started execution.  Only set when `started` is true.", alias="startDate")
    execution_name: Optional[StrictStr] = Field(default=None, description="Name of the started execution, or null when one was already running.", alias="executionName")
    state_machine_arn: Optional[StrictStr] = Field(default=None, description="ARN of the state machine the request targeted.", alias="stateMachineArn")
    running_execution: Optional[RunningExecution] = Field(default=None, description="The execution already in progress.  Only set when `started` is false. ", alias="runningExecution")
    __properties: ClassVar[List[str]] = ["message", "started", "executionArn", "startDate", "executionName", "stateMachineArn", "runningExecution"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StartExecutionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of running_execution
        if self.running_execution:
            _dict['runningExecution'] = self.running_execution.to_dict()
        # set to None if execution_arn (nullable) is None
        # and model_fields_set contains the field
        if self.execution_arn is None and "execution_arn" in self.model_fields_set:
            _dict['executionArn'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['startDate'] = None

        # set to None if execution_name (nullable) is None
        # and model_fields_set contains the field
        if self.execution_name is None and "execution_name" in self.model_fields_set:
            _dict['executionName'] = None

        # set to None if running_execution (nullable) is None
        # and model_fields_set contains the field
        if self.running_execution is None and "running_execution" in self.model_fields_set:
            _dict['runningExecution'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StartExecutionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "started": obj.get("started"),
            "executionArn": obj.get("executionArn"),
            "startDate": obj.get("startDate"),
            "executionName": obj.get("executionName"),
            "stateMachineArn": obj.get("stateMachineArn"),
            "runningExecution": RunningExecution.from_dict(obj["runningExecution"]) if obj.get("runningExecution") is not None else None
        })
        return _obj


